#!/bin/bash
#
#
#
#
clear
var1=`which nikto`
var3=`echo Y`
var4=`echo y`
var5=`echo iniciar`
var6=`echo acrescentar`


echo -e "\033[1;33m xxxxxxxxxxxx \033[0m \033[0;33m'/\'\033[0m \033[1;33m xxxxxxxxxxxx \033[0m"
echo -e "\033[1;33m xxxxxxxxxxx \033[0m \033[0;33m'/cc\'\033[0m \033[1;33m xxxxxxxxxxx \033[0m"
echo -e "\033[1;33m xxxxxxxxxx \033[0m \033[0;33m'/cccc\'\033[0m \033[1;33m xxxxxxxxxx \033[0m"
echo -e "\033[1;33m xxxxxxxxx \033[0m \033[0;33m'/cccccc\'\033[0m \033[1;33m xxxxxxxxx \033[0m"
echo -e "\033[1;33m xxxxxxxx \033[0m \033[0;33m'/cccccccc\'\033[0m \033[1;33m xxxxxxxx \033[0m"
echo -e "\033[1;33m xxxxxxx \033[0m \033[0;33m'/cccccccccc\'\033[0m \033[1;33m xxxxxxx \033[0m"
echo -e "\033[1;33m xxxxxx \033[0m \033[0;33m'/o+88888888+o\'\033[0m \033[1;33m xxxxxx \033[0m"
echo -e "\033[1;33m xxxxx \033[0m'/oe+88888888+eo\'\033[1;33m' xxxxx \033[0m"
echo -e "\033[1;33m xxxx \033[0m'/oec+88888888+ceo\'\033[1;33m xxxx \033[0m"
echo -e "\033[1;33m xxx \033[0m'/oeco+88888888+oceo\'\033[1;33m xxx \033[0m"
echo -e "\033[1;33m xx \033[0m'/oecoe+88888888+eoceo\'\033[1;33m xx \033[0m"
echo -e "\033[1;33m x \033[0m'/______________________\'\033[1;33m x \033[0m"
sleep 10s

if [ $var1 ]
then
echo ""
echo -e " \033[1;35m url com: \033[0m " ' \033[1;34m www. .com .net .br \033[0m'
echo -e " \033[1;35m URL:    \033[0m "
read -p "R:  "  url
echo -e "\033[1;35m portas disponiveis:\033[0m" '\033[1;34m 80,443,22,23 \033[0m'
echo -e " \033[1;35m PORT:    \033[0m "
read -p "R:  "  port
echo -e        "\033[1;32m Y \033[0m"/'\033[1;31m N \033[0m'      
echo -e "\033[1;35m Deseja utilizar Proxy? \033[0m"
read -p "R:  "  pro2
fi

if [[ $pro2 == $var4 ]] || [[ $pro2 == $var3 ]]
then
echo -e "\033[1;36m Ex: \033[0m" '\033[1;34m http://127.0.0.1:8080 \033[0m'
read -p "R:  " pro
echo ""
echo -e "\033[1;35m Deseja utilizar Display? \033[0m"
echo -e "\033[1;32m     Y \033[0m"/'\033[1;31m N \033[0m'
read -p "R:  " disp1
else
echo -e "\033[1;36m Proxy nao selecionado \033[0m"
echo -e "\033[1;35m Deseja utilizar Display? \033[0m"
echo -e "\033[1;32m Y \033[0m"/'\033[1;31m N \033[0m' 
read -p "R:  " disp2
fi

if [[ $disp1 = $var3 ]]  || [[ $disp1 = $var4 ]] || [[ $disp2 = $var3 ]] || [[ $disp2 = $var4 ]]
then
echo "Qual deseja?"
echo -e '\033[1;32m (1) - \033[1;36m " Mostra os enderecos existentes no site. " \033[0m ' 
echo -e '\033[1;32m (2) - \033[1;36m " Mostra os cookies recebidos " \033[0m '
echo -e '\033[1;32m (3) - \033[1;36m " Mostra todas as respostas,200/Ok " \033[0m '
echo -e '\033[1;32m (4) - \033[1;36m " Mostra os enderecos que precisa de permissao " \033[0m '
echo -e '\033[1;32m (D) - \033[1;36m " Mostra as saidas de depuracao. " \033[0m '
echo -e '\033[1;32m (E) - \033[1;36m " Mostra todos erros HTTP. " \033[0m '
echo -e '\033[1;32m (P) - \033[1;36m " Mostra os arquivos e pastas do site. " \033[0m '
echo -e '\033[1;32m (S) - \033[1;36m " Mostra Ips e nomes de Hosts. " \033[0m '
echo -e '\033[1;32m (V) - \033[1;36m " Saida detalhada. " \033[0m '
echo -e "\033[1;34m    informe o numero/letra: \033[0m " 
read -p "R:  " disp
echo -e "\033[1;36m Deseja utilizar Tuning? \033[0m"
echo -e "\033[1;32m Y \033[0m"/'\033[1;31m N \033[0m'
read -p "R:  " turn2
else
echo -e "\033[1;36m Deseja utilizar Tuning? \033[0m"
echo -e "\033[1;32m Y \033[0m"/'\033[1;31m N \033[0m'
read -p "R:  " turn2
fi

if [[ $turn2 = $var3 ]] || [[ $turn2 = $var4 ]]
then
echo ""
echo "Qual Deseja?"
echo -e '\033[1;33m (1) - \033[0;33m " Arquivo interessante/visto em log. " \033[0m '
echo -e '\033[1;33m (2) - \033[0;33m " Configuracao incorreta/arquivo padrao. " \033[0m '
echo -e '\033[1;33m (3) - \033[0;33m " Divulgacao de informacoes. " \033[0m '
echo -e '\033[1;33m (4) - \033[0;33m " Injecao ( XSS / SCRIPT / HTML ). " \033[0m '
echo -e '\033[1;33m (5) - \033[0;33m " Recuperacao Remota de arquivos - Raiz interna da Web. " \033[0m '
echo -e '\033[1;33m (6) - \033[0;33m " Negacao de Servico. " \033[0m '
echo -e '\033[1;33m (7) - \033[0;33m " Recuperacao Remota de arquivos - Largura do servidor. " \033[0m '
echo -e '\033[1;33m (8) - \033[0;33m " Execucao de comando / Shell Remoto. " \033[0m '
echo -e '\033[1;33m (9) - \033[0;33m " Injecao de SQL. " \033[0m '
echo -e '\033[1;33m (0) - \033[0;33m " Upload de arquivos. "	\033[0m '
echo -e '\033[1;33m (a) - \033[0;33m " Bypass de autenticacao. " \033[0m '
echo -e '\033[1;33m (b) - \033[0;33m " Identificao de Softwarr. " \033[0m '
echo -e '\033[1;33m (c) - \033[0;33m " Inclusao remota de fontes. " \033[0m '
echo -e '\033[1;33m (x) - \033[0;33m " Reverse Tuning Options(Incluir todos, exceto os especificados). " \033[0m '
echo ""
echo -e '\033[1;34m    informe o numero/letra: \033[0m '
read -p "R:   " turn
fi

if [[ $turn ]]
then
echo ""
echo -e "\033[1;34m Deseja salvar os resultados em um arquivo? \033[0m"
echo -e "\033[1;32m Y \033[0m"/'\033[1;31m N \033[0m'
read -p "R:   " form1
else
echo -e "\033[1;34m Deseja salvar os resultados em um arquivo? \033[0m "
echo -e "\033[1;32m Y \033[0m"/'\033[1;31m N \033[0m'
read -p "R:   " form2
fi

if [[ $form1 = $var3 ]] || [[ $form1 = $var4 ]] || [[ $form2 = $var3 ]] || [[ $form2 = $var4 ]]
then
echo ""
echo -e "\033[1;34m Qual tipo de formato? \033[0m"
echo -e '\033[1;36m csr - \033[1;33m " Comma-separated-value " \033[0m '
echo -e '\033[1;36m htm - \033[1;33m " html format " \033[0m '
echo -e '\033[1;36m mbe - \033[1;33m " log to metasploit " \033[0m '
echo -e '\033[1;36m txt - \033[1;33m " plain text " \033[0m '
echo -e '\033[1;36m xml - \033[1;33m " xml format " \033[0m '
echo ""
read -p "R:   " form
echo -e '\033[1;32m Deseja \033[1;31m Iniciar \033[1;34m ou \033[1;36m Acrescentar algo?  \033[0m '
echo ""
echo -e "\033[1;32m iniciar \033[0m"/'\033[1;31m acrescentar \033[0m'
read -p "R:   " inc1
else
echo -e '\033[1;32m Deseja \033[1;31m iniciar \033[1;34m ou \033[1;36m Acrescentar algo? \033[0m '
read -p "R:   " inc2
fi

if [[ $inc1 = $var5 ]] || [[ $inc2 = $var5 ]]
then
echo -e "\033[1;32m INICIANDO \033[0m"
fi

if [[ $url && $port &&  $pro  && $disp && $turn && $form ]]
then
ini2=`nikto -h $url -port $port -useproxy $pro -Display $disp -Tuning $turn -o $form `
fi

if [[ $url ]] && [[ $port ]] && [[ $pro ]] && [[ $disp ]] && [[ $form ]]
then
ini3=`nikto -h $url -port $port -useproxy $pro -Display $disp -o $form `
fi

if [[ $url ]] && [[ $port ]] && [[ $pro ]] && [[ $form ]]
then
ini4=`nikto -h $url -port $port -useproxy $pro -o $form `
fi

if [[ $url ]] && [[ $port ]] && [[ $disp ]] && [[ $form ]]
then
ini6=`nikto -h $url -port $port -Display $disp -o $form `
fi

if [[ $url ]] && [[ $port ]] && [[ $form ]]
then
ini7=`nikto -h $url -port $port -o $form `
fi

if [[ $url ]] && [[ $port ]]
then
ini8=`nikto -h $url -port $port`
fi
