#!/bin/bash
#
#
#
#
clear
var1=`which nikto`
var3=`echo Y`
var4=`echo y`
var5=`echo iniciar`
var6=`echo acrescentar`

echo -e '  x x x x x x x x x x x' " \033[0;35m  ============================== \033[0m "
echo -e ' x x x x x x x x x x x x' " \033[1;33m â============================== \033[0m "
echo -e ' x x  \033[1;36m criado por:\033[0m   x x' " \033[1;34m ============================== \033[0m "
echo -e ' x x    \033[1;36m H4V3R7\033[0m      x x' " \033[1;31m ============================== \033[0m "
echo -e '  x      \033[1;36m leia:\033[0m       x' "  \033[1;35m ============================== \033[0m "
echo -e ' x x   \033[1;36m readme.md\033[0m    x x' " \033[1;36m ============================== \033[0m "
echo -e ' x x x x x x x x x x x x' " \033[1;32m ============================== \033[0m "
echo -e '  x x x x x x x x x x x ' " \033[0;32m ============================== \033[0m "

sleep 10s
if [[ $var1 ]] 
then
echo ""
echo -e " \033[1;35m url com: \033[0m " ' \033[1;34m www. .com .net .br \033[0m'
echo -e " \033[1;35m URL:    \033[0m "
read -p "R:  "  url
echo -e "\033[1;35m portas disponiveis:\033[0m" '\033[1;34m 80,443,22,23 \033[0m'
echo -e " \033[1;35m PORT:    \033[0m "
read -p "R:  "  port
echo -e        "\033[1;32m Y \033[0m"/'\033[1;31m N \033[0m'      
echo -e "\033[1;35m Deseja utilizar Proxy? \033[0m"
read -p "R:  "  pro2
fi

if [[ $pro2 == $var4 ]] || [[ $pro2 == $var3 ]]
then
echo -e "\033[1;36m Ex: \033[0m" '\033[1;34m http://127.0.0.1:8080 \033[0m'
read -p "R:  " pro
echo ""
echo -e "\033[1;35m Deseja utilizar Display? \033[0m"
echo -e "\033[1;32m     Y \033[0m"/'\033[1;31m N \033[0m'
read -p "R:  " disp1
else
echo -e "\033[1;36m Proxy nao selecionado \033[0m"
echo -e "\033[1;35m Deseja utilizar Display? \033[0m"
echo -e "\033[1;32m Y \033[0m"/'\033[1;31m N \033[0m' 
read -p "R:  " disp2
fi

if [[ $disp1 = $var3 ]]  || [[ $disp1 = $var4 ]] || [[ $disp2 = $var3 ]] || [[ $disp2 = $var4 ]]
then
echo "Qual deseja?"
echo -e '\033[1;32m (1) - \033[1;36m " Mostra os enderecos existentes no site. " \033[0m ' 
echo -e '\033[1;32m (2) - \033[1;36m " Mostra os cookies recebidos " \033[0m '
echo -e '\033[1;32m (3) - \033[1;36m " Mostra todas as respostas,200/Ok " \033[0m '
echo -e '\033[1;32m (4) - \033[1;36m " Mostra os enderecos que precisa de permissao " \033[0m '
echo -e '\033[1;32m (D) - \033[1;36m " Mostra as saidas de depuracao. " \033[0m '
echo -e '\033[1;32m (E) - \033[1;36m " Mostra todos erros HTTP. " \033[0m '
echo -e '\033[1;32m (P) - \033[1;36m " Mostra os arquivos e pastas do site. " \033[0m '
echo -e '\033[1;32m (S) - \033[1;36m " Mostra Ips e nomes de Hosts. " \033[0m '
echo -e '\033[1;32m (V) - \033[1;36m " Saida detalhada. " \033[0m '
echo -e "\033[1;34m    informe o numero/letra: \033[0m " 
read -p "R:  " disp
echo -e "\033[1;36m Deseja utilizar Tuning? \033[0m"
echo -e "\033[1;32m Y \033[0m"/'\033[1;31m N \033[0m'
read -p "R:  " turn2
else
echo -e "\033[1;36m Deseja utilizar Tuning? \033[0m"
echo -e "\033[1;32m Y \033[0m"/'\033[1;31m N \033[0m'
read -p "R:  " turn2
fi

if [[ $turn2 = $var3 ]] || [[ $turn2 = $var4 ]]
then
echo ""
echo "Qual Deseja?"
echo -e '\033[1;33m (1) - \033[0;33m " Arquivo interessante/visto em log. " \033[0m '
echo -e '\033[1;33m (2) - \033[0;33m " Configuracao incorreta/arquivo padrao. " \033[0m '
echo -e '\033[1;33m (3) - \033[0;33m " Divulgacao de informacoes. " \033[0m '
echo -e '\033[1;33m (4) - \033[0;33m " Injecao ( XSS / SCRIPT / HTML ). " \033[0m '
echo -e '\033[1;33m (5) - \033[0;33m " Recuperacao Remota de arquivos - Raiz interna da Web. " \033[0m '
echo -e '\033[1;33m (6) - \033[0;33m " Negacao de Servico. " \033[0m '
echo -e '\033[1;33m (7) - \033[0;33m " Recuperacao Remota de arquivos - Largura do servidor. " \033[0m '
echo -e '\033[1;33m (8) - \033[0;33m " Execucao de comando / Shell Remoto. " \033[0m '
echo -e '\033[1;33m (9) - \033[0;33m " Injecao de SQL. " \033[0m '
echo -e '\033[1;33m (0) - \033[0;33m " Upload de arquivos. "	\033[0m '
echo -e '\033[1;33m (a) - \033[0;33m " Bypass de autenticacao. " \033[0m '
echo -e '\033[1;33m (b) - \033[0;33m " Identificao de Softwarr. " \033[0m '
echo -e '\033[1;33m (c) - \033[0;33m " Inclusao remota de fontes. " \033[0m '
echo -e '\033[1;33m (x) - \033[0;33m " Reverse Tuning Options(Incluir todos, exceto os especificados). " \033[0m '
echo ""
echo -e '\033[1;34m    informe o numero/letra: \033[0m '
read -p "R:   " turn
fi

if [[ $turn ]]
then
echo ""
echo -e "\033[1;34m Deseja salvar os resultados em um arquivo? \033[0m"
echo -e "\033[1;32m Y \033[0m"/'\033[1;31m N \033[0m'
read -p "R:   " form1
else
echo -e "\033[1;34m Deseja salvar os resultados em um arquivo? \033[0m "
echo -e "\033[1;32m Y \033[0m"/'\033[1;31m N \033[0m'
read -p "R:   " form2
fi

if [[ $form1 = $var3 ]] || [[ $form1 = $var4 ]] || [[ $form2 = $var3 ]] || [[ $form2 = $var4 ]]
then
echo ""
echo -e "\033[1;34m Qual tipo de formato? \033[0m"
echo -e '\033[1;36m csr - \033[1;33m " Comma-separated-value " \033[0m '
echo -e '\033[1;36m htm - \033[1;33m " html format " \033[0m '
echo -e '\033[1;36m mbe - \033[1;33m " log to metasploit " \033[0m '
echo -e '\033[1;36m txt - \033[1;33m " plain text " \033[0m '
echo -e '\033[1;36m xml - \033[1;33m " xml format " \033[0m '
echo ""
read -p "R:   " form
echo -e '\033[1;32m Deseja \033[1;31m Iniciar \033[1;34m ou \033[1;36m Acrescentar algo?  \033[0m '
echo ""
echo -e "\033[1;32m iniciar \033[0m"/'\033[1;31m acrescentar \033[0m'
read -p "R:   " inc1
else
echo -e '\033[1;32m Deseja \033[1;31m iniciar \033[1;34m ou \033[1;36m Acrescentar algo? \033[0m '
read -p "R:   " inc2
fi

if [[ $inc1 = $var5 ]] || [[ $inc2 = $var5 ]]
then
echo -e "\033[1;32m INICIANDO \033[0m"
else
echo -e "\033[1;31m ERROR: iniciar/acrescentar \033[0m"
exit
fi

func1(){
case $pro in
127.0.0.1:*) echo $pro2;;
esac
}

func2(){
case $disp in
1)echo 1;;
2)echo 2;;
3)echo 3;;
4)echo 4;;
D)echo D;;
E)echo E;;
P)echo P;;
S)echo S;;
V)echo V;;
*)exit;;
esac
}

func3(){
case $turn in
1)echo 1;;
2)echo 2;;
3)echo 3;;
4)echo 4;;
5)echo 5;;
6)echo 6;;
7)echo 7;;
8)echo 8;;
9)echo 9;;
a)echo a;;
b)echo b;;
c)echo c;;
x)echo x;;
*)exit;;
esac
}

func4(){
case $form in
csr)echo csr;;
htm)echo htm;;
mbe)echo mbe;;
txt)echo txt;;
xml)echo xml;;
*)exit;;
esac
}

func5(){
case $inc1 in
iniciar)echo 'iniciar';;
acrescentar)
var5=acres
read -p "Acrescenta aqui o comando e argumento:   " acres
;;
esac
}

func6(){
case $inc2 in
iniciar)echo 'iniciar';;
acrescentar)
var5=acres
read -p "Acrescenta aqui o comando e argumento:   " acres
;;
esac
}

f1=`func1`
f2=`func2`
f3=`func3`
f4=`func4`
f5=`func5`
f6=`func6`

if [[ $url ]] && [[ $port ]] && [[ $f1 ]] && [[ $f2 ]] && [[ $f3 ]] && [[ $f4 ]]
then
nikto -h $url -port $port -useproxy $pro -Display $disp -Tuning $turn -o $form $acres
exit
fi

if [[ $url ]] && [[ $port ]] && [[ $f1 ]] && [[ $f2 ]] && [[ $f4 ]]
then
ini3=nikto -h $url -port $port -useproxy $pro -Display $disp -o $form $acres 
exit
fi

if [[ $url ]] && [[ $port ]] && [[ $f1 ]] && [[ $f4 ]]
then
nikto -h $url -port $port -useproxy $pro -o $form $acres
exit
fi

if [[ $url ]] && [[ $port ]] && [[ $f2 ]] && [[ $f3 ]] && [[ $f4 ]]
then
nikto -h $url -port $port -Display $disp -Tuning $turn -o $form $acres
exit
fi

if [[ $url ]] && [[ $port ]] && [[ $f3 ]] && [[ $f4 ]]
then
nikto -h $url -port $port -Tuning $turn -o $form $acres
exit
fi

if [[ $url ]] && [[ $port ]] && [[ $f3 ]]
then
nikto -h $url -port $port -Tuning $turn $acres
exit
fi

if [[ $url ]] && [[ $port ]] && [[ $f3 ]] && [[ $f1 ]] && [[ $f4 ]]
then
nikto -h $url -port $port -Tuning $turn -useproxy $pro -o $form $acres
exit
fi

if [[ $url ]] && [[ $port ]] && [[ $f3 ]] && [[ $f1 ]]
then
nikto -h $url -port $port -Tuning $turn -useproxy $pro $acres
exit
fi

if [[ $url ]] && [[ $port ]] && [[ $f2 ]] && [[ $f3 ]]
then
nikto -h $url -port $port -Tuning $turn -Display $disp $acres
exit
fi

if [[ $url ]] && [[ $port ]]
then
nikto -h $url -port $port $acres
exit
fi

if [[ $url ]] && [[ $port ]] && [[ $form ]]
then
nikto -h $url -port $port $acres
exit
fi
