#!/bin/bash
#
#
#
#

clear
var1=`which youtube-dl`
var3=`echo Y`
var4=`echo y`
var5=`echo iniciar`
var6=`echo acrescentar`
audio2=`echo audio`
video2=`echo video`

echo -e '  x x x x x x x x x x x' " \033[0;35m  ============================== \033[0m "
echo -e ' x x x x x x x x x x x x' " \033[1;33m â============================== \033[0m "
echo -e ' x x  \033[1;36m criado por:\033[0m   x x' " \033[1;34m ============================== \033[0m "
echo -e ' x x    \033[1;36m H4V3R7\033[0m      x x' " \033[1;31m ============================== \033[0m "
echo -e '  x      \033[1;36m leia:\033[0m       x' "  \033[1;35m ============================== \033[0m "
echo -e ' x x   \033[1;36m readme.md\033[0m    x x' " \033[1;36m ============================== \033[0m "
echo -e ' x x x x x x x x x x x x' " \033[1;32m ============================== \033[0m "
echo -e '  x x x x x x x x x x x ' " \033[0;32m ============================== \033[0m "

sleep 10s 
if [ $var1 ] 
then
echo -e "\033[1;34m Deseja baixar audio ou video? \033[0m" 
echo -e "\033[1;32m audio \033[0m " / '\033[1;33m video \033[0m'
read -p "R:    " you
fi

if [ $f1 ]
then
echo -e "\033[1;31m ERROR \033[0m"
fi

if [[ $you = $audio2 ]]
then
echo -e "\033[1;34m Deseja qual formato de audio? \033[0m"
echo -e "\033[1;36m mp3 \033[0m"
echo -e "\033[1;36m mpeg \033[0m"
read -p "R:    " audio
fi

if [[ $you = $video2 ]]
then
echo -e "\033[1;34m Deseja qual formato de video? \033[0m"
echo -e "\033[1;36m mp4 \033[0m"
echo -e "\033[1;36m avi \033[0m"
echo -e "\033[1;36m flv \033[0m"
read -p "R:    " video
fi

if [ $video ]
then
echo -e "\033[1;34m Deseja que qualidade? \033[0m"
echo -e "\033[1;36m ex: 128,360,420,720,1080 \033[0m"
echo -e "\033[1;33m Obs: \033[0;34 veja tambem se o video possui essa qualidade. \033[0m"
read -p "R:    " qualidade
fi

if [ $qualidade ]
then
echo -e "\033[1;34m Deseja usar legendas? \033[0m"
echo -e "\033[1;36m ex: en,pt,es\033[0m"
read -p "R:    " legenda
fi

if [ $audio ]
then
echo -e "\033[1;34m deseja colocar titulo?\033[0m"
echo -e "\033[1;36m ex: LollaPaloza\033[0m"
read -p "R:    " audiotitulo
fi

func1(){
case $you in
video)echo "video";;
audio)echo "audio";;
*) echo -e "\033[1;31m ERROR \033[0m"
exit;;
esac
}

f1=`func1`
